# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 04:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFRCStreaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_times', models.IntegerField(default=0, help_text='The number of times you are doing FRCs in a day')),
                ('last_day', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfrcstreaks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
