# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 04:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180306_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfrcstreaks',
            name='last_day',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 4, 11, 45, 731298, tzinfo=utc)),
        ),
    ]
