# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeboundtasks',
            name='percent_completed',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
