# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBoundTasksSubtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('subtask', models.TextField()),
                ('tbt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getsubtasks', to='tasks.TimeBoundTasks')),
            ],
        ),
    ]
