# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 02:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(default=datetime.datetime(2017, 12, 19, 2, 15, 55, 560556, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
