# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_timeboundtaskssubtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeboundtaskssubtask',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tbtsubtasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
