# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_timeboundtaskssubtask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeboundtaskssubtask',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
