# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180105_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeboundtasks',
            name='units_completed',
            field=models.FloatField(default=0),
        ),
    ]
