# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_timeboundtaskssubtask_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeboundtaskssubtask',
            old_name='status',
            new_name='done',
        ),
    ]
