# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_auto_20180112_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useraims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
