# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 14:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_customizations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customizations',
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default=datetime.datetime(2017, 11, 25, 14, 57, 27, 110957, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
