# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoticon', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion', to='taggit.Tag')),
            ],
            options={
                'verbose_name': 'Emotions',
                'verbose_name_plural': 'Emotions',
            },
        ),
        migrations.CreateModel(
            name='TaggedEmotionsAfter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotion_tracker.EmotionJournal')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_tracker_taggedemotionsafter_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggedemotionsafter_emotionsafter', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedEmotionsBefore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotion_tracker.EmotionJournal')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_tracker_taggedemotionsbefore_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggedemotionsbefore_emotionsbefore', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emotionjournal',
            name='emotions_after',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='emotion_tracker.TaggedEmotionsAfter', to='taggit.Tag', verbose_name='Emotions After'),
        ),
        migrations.AddField(
            model_name='emotionjournal',
            name='emotions_before',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='emotion_tracker.TaggedEmotionsBefore', to='taggit.Tag', verbose_name='Emotions Before'),
        ),
    ]
