# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedemotionsafter',
            name='a',
        ),
        migrations.RemoveField(
            model_name='taggedemotionsbefore',
            name='a',
        ),
    ]
