# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FRCScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_it_statement', models.TextField()),
                ('replace_it_statement', models.TextField()),
                ('connect_statement', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
