# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0002_frcscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='frcscript',
            name='trigger',
            field=models.TextField(default='Something'),
            preserve_default=False,
        ),
    ]
