# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 04:49
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0002_auto_20171218_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionjournal',
            name='emotions_after',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='emotion_tracker.TaggedEmotionsAfter', to='taggit.Tag', verbose_name='Emotions After'),
        ),
        migrations.AlterField(
            model_name='emotionjournal',
            name='emotions_before',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='emotion_tracker.TaggedEmotionsBefore', to='taggit.Tag', verbose_name='Emotions Before'),
        ),
    ]
