# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0003_auto_20171219_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionjournal',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emotionjournal',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotions',
            name='color',
            field=models.CharField(default='grey', max_length=100),
        ),
    ]
