# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0004_auto_20171224_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotions',
            name='color',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
