# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility_apps.gym_tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=255)),
                ('muscle_group', models.CharField(max_length=300)),
                ('sets', models.IntegerField(default=1)),
                ('reps', models.IntegerField(default=1)),
                ('max_weight', models.FloatField(default=1)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=utility_apps.gym_tracker.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('order_of_performing', models.IntegerField(default=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_days', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramExcerciseMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(default=1)),
                ('excercises', models.ManyToManyField(to='gym_tracker.Exercise')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getexcercises', to='gym_tracker.Program')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgramMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_tracker.Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
