# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programexcercisemap',
            name='day_name',
            field=models.CharField(default='Chest Day', max_length=255),
        ),
    ]
