# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 03:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(default=datetime.datetime(2017, 12, 24, 3, 40, 29, 912136, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
    ]
