# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0002_programexcercisemap_day_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programexcercisemap',
            options={'ordering': ['weekday']},
        ),
    ]
