# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0003_auto_20171224_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramExcerciseMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='name',
            new_name='exercise_name',
        ),
        migrations.AddField(
            model_name='exercise',
            name='max_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='programexcercisemap',
            name='excercises',
            field=models.ManyToManyField(to='gym_tracker.Exercise'),
        ),
        migrations.AddField(
            model_name='programexcercisemap',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getprogramname', to='gym_tracker.Program'),
        ),
    ]
