# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0003_auto_20180203_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='programexcercisemap',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=100),
        ),
    ]
