# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import utility_apps.gym_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0004_auto_20171224_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=utility_apps.gym_tracker.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
