# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0005_auto_20171224_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
