# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0006_exercise_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='number_of_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='programexcercisemap',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getexcercises', to='gym_tracker.Program'),
        ),
    ]
