# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0008_userprogrammap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogrammap',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gym_tracker.Program'),
        ),
    ]
