# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0011_exercise_order_of_performing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='max_weight',
            field=models.FloatField(default=1),
        ),
    ]
